site_name: 時を超えて語るもの―史料と美術の名宝―
theme:
  name: material # readthedocs
  language: ja
  feature:
    tabs: true
    navigation: top

extra:
  search:
    language: jp

extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "css/custom.css"

markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

plugins:
  - search
  - awesome-pages

nav:
    - index.md
    - 第一部　史料・美術展示:
        - （１）公家の世界: 001.md
        - （２）武家文書の世界: 012.md
        - （４）国絵図の世界: 014.md
    - 第二部:
        - 東京大学史料編纂所のあゆみ: 020.md